FROM maven:3.9.11-eclipse-temurin-21 AS build
WORKDIR /source
COPY dayanfood-backend/pom.xml .
COPY dayanfood-backend/src ./src
RUN --mount=type=cache,target=/root/.m2 mvn -q -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /source/target/dayanfood-backend-*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
